---
language: node_js
node_js:
  - "6.10.0"

dist: trusty
sudo: false

addons:
  apt:
    packages:
      - google-chrome-stable

cache:
  directories:
    - node_modules

before_install:
  - npm config set spin false
  - npm install -g bower
  - bower --version

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start &
  - sleep 3

install:
  - npm install
  - bower install

script:
  - npm test

notifications:
  slack: omordn:TmqvxTNAAcwkwWuPIkwR5Lkl
