---
language: node_js
node_js:
  - "6.10.0"

dist: trusty
sudo: false

addons:
  apt:
    packages:
      - google-chrome-stable

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - npm config set spin false
  # - npm install -g bower
  # - bower --version

install:
  - yarn install
  # This is a workaround to fix the 'Cannot find module'
  # bug. The bug is with yarn:
  # (https://github.com/yarnpkg/yarn/issues/1981)
  - npm rebuild node-sass
  # - bower install

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start &
  - sleep 3

script:
  - yarn run test

notifications:
  slack: omordn:TmqvxTNAAcwkwWuPIkwR5Lkl
